In [106]:
import pandas as pd
import numpy as np

In [131]:
dataset = pd.read_csv("data/PTC.csv")
dataset
pd. set_option('display.max_columns', 100) 
pd. set_option('display.max_rows', None)

In [145]:
dataset_columns = (dataset.isnull().sum() > len(dataset)*0.05)
dataset_columns.where(dataset_columns==True).dropna()

ID                       NaN
Sex                      NaN
Age                      NaN
Height                   NaN
Weight                   NaN
ColdSens                 NaN
ColdExp                  NaN
Workhr                   NaN
Coffeeintake             NaN
Vote_time                NaN
therm_sens               NaN
therm_pref               NaN
location                 NaN
mean.Temperature_60     True
grad.Temperature_60     True
sd.Temperature_60       True
mean.Temperature_480    True
grad.Temperature_480    True
sd.Temperature_480      True
mean.Humidity_60        True
grad.Humidity_60        True
sd.Humidity_60          True
mean.Humidity_480       True
grad.Humidity_480       True
sd.Humidity_480         True
mean.Winvel_60          True
grad.Winvel_60          True
sd.Winvel_60            True
mean.Winvel_480         True
grad.Winvel_480         True
sd.Winvel_480           True
mean.Solar_60           True
grad.Solar_60           True
sd.Solar_60             True
mean.Solar_480          True
grad.Solar_480          True
sd.Solar_480            True
mean.hr_5               True
grad.hr_5               True
sd.hr_5                 True
mean.hr_15              True
grad.hr_15              True
sd.hr_15                True
mean.hr_60              True
grad.hr_60              True
sd.hr_60                True
mean.WristT_5           True
grad.WristT_5           True
sd.WristT_5             True
mean.WristT_15          True
grad.WristT_15          True
sd.WristT_15            True
mean.WristT_60          True
grad.WristT_60          True
sd.WristT_60            True
mean.AnkleT_5           True
grad.AnkleT_5           True
sd.AnkleT_5             True
mean.AnkleT_15          True
grad.AnkleT_15          True
sd.AnkleT_15            True
mean.AnkleT_60          True
grad.AnkleT_60          True
sd.AnkleT_60            True
mean.PantT_5            True
grad.PantT_5            True
sd.PantT_5              True
mean.PantT_15           True
grad.PantT_15           True
sd.PantT_15             True
mean.PantT_60           True
grad.PantT_60           True
sd.PantT_60             True
mean.act_5              True
grad.act_5              True
sd.act_5                True
mean.act_15             True
grad.act_15             True
sd.act_15               True
mean.act_60             True
grad.act_60             True
sd.act_60               True
dtype: object

In [29]:
object_columns = [column for column in dataset.columns if dataset[column].dtype == 'O']

In [103]:
def convert_nominal(dataset):
    object_columns = [column for column in dataset.columns if dataset[column].dtype == 'O']
    object_columns = object_columns
    dummies = []
    for column in [object_columns]:
        dummies.append(pd.get_dummies(dataset[column]))
        dataset = dataset.drop(column, axis='columns')
    dataset = pd.concat([dataset, *dummies], axis=1)
    return dataset

In [104]:
ds = convert_nominal(dataset)

In [105]:
ds

,ID,Age,Height,Weight,ColdSens,ColdExp,Workhr,Coffeeintake,therm_sens,therm_pref,...,Vote_time_6/8/2017 16:24,Vote_time_6/8/2017 17:18,Vote_time_6/8/2017 17:26,Vote_time_6/8/2017 17:36,Vote_time_6/8/2017 18:08,Vote_time_6/8/2017 18:22,Vote_time_6/8/2017 3:18,Vote_time_6/8/2017 4:18,Vote_time_6/8/2017 4:33,Vote_time_6/8/2017 7:37
0,3,31,1.70,55.0,3.5,1.6,4.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,31,1.70,55.0,3.5,1.6,4.0,0.0,0.6,0,...,0,0,0,0,0,0,0,0,0,0
2,3,31,1.70,55.0,3.5,1.6,4.0,0.0,-0.1,0,...,0,0,0,0,0,0,0,0,0,0
3,3,31,1.70,55.0,3.5,1.6,4.0,0.0,-0.1,0,...,0,0,0,0,0,0,0,0,0,0
4,3,31,1.70,55.0,3.5,1.6,4.0,0.0,0.1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3838,12,21,1.75,61.0,3.0,0.0,1.8,0.0,-1.1,1,...,0,0,0,0,0,0,0,0,0,0
3839,12,21,1.75,61.0,3.0,0.0,1.8,0.0,-1.4,1,...,0,0,0,0,0,0,0,0,0,0
3840,12,21,1.75,61.0,3.0,0.0,1.8,0.0,-0.2,0,...,0,0,0,0,0,0,0,0,0,0
3841,12,21,1.75,61.0,3.0,0.0,1.8,0.0,-1.4,1,...,0,0,0,0,0,0,0,0,0,0
3842,12,21,1.75,61.0,3.0,0.0,1.8,0.0,-1.1,1,...,0,0,0,0,0,0,0,0,0,0