In [2]:
import pandas as pd
import numpy as np

In [70]:
dataset = pd.read_csv("data/PTC.csv")

In [29]:
object_columns = [column for column in dataset.columns if dataset[column].dtype == 'O']

In [93]:
def convert_nominal(dataset):
    object_columns = [column for column in dataset.columns if dataset[column].dtype == 'O']
    object_columns = object_columns[0]
    dummies = []
    for column in [object_columns]:
        dummies.append(pd.get_dummies(dataset[column]))
        dataset.drop(column, axis=columns)
    dataset = pd.concat([dataset, *dummies], axis=1)
    for column in [object_columns]:

    return dataset

In [94]:
ds = convert_nominal(dataset)

KeyError: "['Sex'] not found in axis"

In [78]:
ds

,ID,Sex,Age,Height,Weight,ColdSens,ColdExp,Workhr,Coffeeintake,Vote_time,...,grad.act_5,sd.act_5,mean.act_15,grad.act_15,sd.act_15,mean.act_60,grad.act_60,sd.act_60,Female,Male
0,3,Male,31,1.70,55.0,3.5,1.6,4.0,0.0,5/1/2017 10:10,...,NaN,NaN,9.145558,0.013805,1.663009,9.126026,3.282967e-03,1.045788e+00,0,1
1,3,Male,31,1.70,55.0,3.5,1.6,4.0,0.0,5/1/2017 10:35,...,NaN,NaN,7.036822,NaN,NaN,9.249029,1.246707e-01,8.194081e-01,0,1
2,3,Male,31,1.70,55.0,3.5,1.6,4.0,0.0,5/1/2017 11:40,...,0.000001,0.000001,9.249484,0.000001,0.000001,9.090590,-2.016959e-02,8.859536e-01,0,1
3,3,Male,31,1.70,55.0,3.5,1.6,4.0,0.0,5/1/2017 12:00,...,NaN,NaN,9.249485,NaN,NaN,9.249485,-1.690000e-07,6.500000e-07,0,1
4,3,Male,31,1.70,55.0,3.5,1.6,4.0,0.0,5/1/2017 12:07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3838,12,Male,21,1.75,61.0,3.0,0.0,1.8,0.0,12/18/2016 19:10,...,NaN,NaN,NaN,NaN,NaN,10.664267,-4.960000e-07,1.190000e-06,0,1
3839,12,Male,21,1.75,61.0,3.0,0.0,1.8,0.0,12/18/2016 21:15,...,NaN,NaN,NaN,NaN,NaN,9.329686,-1.751793e-02,4.450424e-01,0,1
3840,12,Male,21,1.75,61.0,3.0,0.0,1.8,0.0,12/18/2016 23:00,...,NaN,NaN,NaN,NaN,NaN,10.769410,NaN,NaN,0,1
3841,12,Male,21,1.75,61.0,3.0,0.0,1.8,0.0,12/19/2016 1:17,...,NaN,NaN,10.553272,NaN,0.620557,9.850867,3.036039e-02,1.301096e+00,0,1
3842,12,Male,21,1.75,61.0,3.0,0.0,1.8,0.0,12/19/2016 11:47,...,NaN,NaN,9.666763,-0.107586,0.840812,9.666763,-1.075858e-01,8.408118e-01,0,1